### PR TITLE
Refactoring HAR generation to be inline with Chromium

### PR DESCRIPTION
**Pull request by beenanner**
Mirroring Chromium HarEntry.js as much as possible. Still needs work on blocking and startDateTime of entries.

[HAREntry.js from Chromium](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/devtools/front_end/sdk/HAREntry.js)

### CODE REVIEW

**Comment by tobli** [comment]
Thanks. Great to have the Chromium source to compare with.

**Comment by soulgalore** [comment]
One thing: are we sure it's right in chromium? :) I think our hars looked better than Chrome ... lets re-check.

**Comment by tobli** [comment]
True, Chrome isn't the one source of truth. It's good that we can check Firefox as well, take inspiration from both and make it even better. To refine even further I think we need to set up a local test server, with predictable download times, connection throttling etc.

**Comment by soulgalore** [comment]
I thought (but not 100%) that our har shows dns lookup etc that exported har from Chrome misses. But lets check that again. Its cool to compare how chromium do their thing :)

**Comment by parangsjo** [comment]
Hey,

This is just something really astonishing, I'm telling you, you have to take a look <http://thiwofyque.thegoodicecompany.com/xyadzl>

pa@rangsjo.com

**Pull request merged**
