### PR TITLE
Update custom header examples

### PR DESCRIPTION
**Pull request by okor**
Custom header example will now work.

Aligns with changes made as a result of this issue https://github.com/tobli/browsertime/issues/97

### CODE REVIEW

**Comment by tobli** [comment]
Thanks!

**Comment by okor** [comment]
Sure thing. Is it normal for this build to fail though? https://ci.appveyor.com/project/tobli/browsertime/build/1.0.104

**Comment by tobli** [comment]
I'd been experimenting with AppVeyor for CI tests on IE. Hadn't gotten it to a working setup. But apparently it was still active for PRs. It was just adding noise, so it's removed now. Might try to get it working in a dedicated branch, but not a high priority.

**Comment by okor** [comment]
@tobli Understood. Just wanted to make sure my README change didn't somehow break the build. That would have been a first, to the best of my knowledge.

**Pull request merged**
